### ISSUE TITLE
missing src directory?

### ISSUE THREAD

**Issue by wangqi01** [K-miran/HELR#1]
Hi , I'd just run the implementation failed,  have you missed upload "src" directory ,if you could, plz upload it? or it should write by myself reffered to HEAAN?

**Comment by K-miran** [comment]
I am so sorry for the trouble. You first should download the HEAAN library. If you install it, then you can use some functions in "src" folders of the library.

**Comment by wangqi01** [comment]
yes , I have done this. But still can not find some files,like "SchemeAux.h" which is not in HEAAN. If it is possible, could you please send to my email(qwang01@foxmail.com) or upload ? Thanks!

**Comment by K-miran** [comment]
I am so sorry for this trouble. I forget that we changed our HEAAN library after the implementation of HELR. 
I uploaded some files for installing the HEAAN library I used for experiment. 
If you have some question, let me know.

Best,
Miran Kim

**Comment by wangqi01** [comment]
Thanks a lot!

Best wishes,
Wang Qi
